### ISSUE TITLE
Server PHP "maximum execution time" set too low

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/ld4pe-general#29]
@davidwtalley & @josephrchapman, on Oct. 15, I posted to our Architecture Google Group that I was getting timing out error messages saying that it is likely due to "maximum execution time" being set too low in the server's PHP configuration. I have attached an image of the error message this morning. I am not sure who is in the best position to change the setting from "30" to "180".

![php_settings](https://cloud.githubusercontent.com/assets/2939046/10715229/e69cdbd2-7acb-11e5-8a2c-e378819f1b34.png)

**Comment by josephrchapman** [comment]
Hi Stuart,

I've made a change to the .htaccess.  Can you please check if this is now fixed?

**Comment by stuartasutton** [comment]
Hmm. I do not seem to be getting the message when I am working on explore.dublincore.net, but still get it when working on dublincore.net. Are there different .htaccess files?

**Comment by davidwtalley** [comment]
No,  only one htaccess for the multi-site. I thought that timeout setting is in php.ini which is upstream of the WP install - it's part of the PHP platform. Apparently it can be set in htaccess,  as well. I will see if I can get that done today.
